[FEATURE] Back-end boiler plate
base39/entrevista-tecnica pull request #2
Opened 2022-02-21 13:03 UTC by montedonioluiz

Novo boiler plate para a etapa de live-coding dos candidatos a back-end

2022-02-21 13:34 UTC, MatheusChignolli requested changes

2022-02-21 13:34 UTC, MatheusChignolli commented on backend-boiler-plate/insomnia_collection.json
> +{"_type":"export","__export_format":4,"__export_date":"2022-02-21T12:50:21.439Z","__export_source":"insomnia.desktop.app:v2021.7.2","resources":[{"_id":"req_d3ed76866ac143ec8160a9c83c06ed7e","parentI
Dúvida, essa importação de config funciona também no Postman? Pergunto mais para entender se prende o entrevistado a usar o insomnia.

2022-02-21 13:34 UTC, MatheusChignolli commented on backend-boiler-plate/src/routes/user.ts
> +
```suggestion
```

2022-02-21 13:48 UTC, montedonioluiz commented on backend-boiler-plate/insomnia_collection.json
> +{"_type":"export","__export_format":4,"__export_date":"2022-02-21T12:50:21.439Z","__export_source":"insomnia.desktop.app:v2021.7.2","resources":[{"_id":"req_d3ed76866ac143ec8160a9c83c06ed7e","parentI
Esta configuração foi gerada a partir do Insomnia e creio que não seja compatível com o Postman. Inclui agora no readme do repo que o candidato pode utilizar o programa que melhor preferir. Podemos incluir uma config do postman também, acha que seria interessante?

2022-02-21 20:12 UTC, MatheusChignolli commented on backend-boiler-plate/insomnia_collection.json
> +{"_type":"export","__export_format":4,"__export_date":"2022-02-21T12:50:21.439Z","__export_source":"insomnia.desktop.app:v2021.7.2","resources":[{"_id":"req_d3ed76866ac143ec8160a9c83c06ed7e","parentI
Se caso não for muito complicado de fazer, eu acho que seria para facilitar para o usuário e focar no técnico pois são ferramentas que podem ser facilmente aprendidas, saca?

2022-02-23 17:26 UTC, Tautorn approved these changes

2022-02-23 17:50 UTC, Tautorn commented
Poderia mudar o nome da branch master para main?

2022-02-23 17:52 UTC, montedonioluiz commented
> Poderia mudar o nome da branch master para main?

acho que nao tenho permissão... maximo q eu posso fazer é criar uma main a partir da master mas n sei se posso torná-la default e apagar a master :/

2022-02-24 12:12 UTC, AmilsonJunior approved these changes

2022-02-24 20:16 UTC, MatheusChignolli approved these changes

2022-03-04 11:56 UTC, merged